# Rate limit Settings

RATELIMIT_RATE_TWITTER = "3/m"
RATELIMIT_KEY = "user"

RATELIMIT_NEWSLETTER_RATE = 3
RATELIMIT_NEWSLETTER_WINDOW = 60  # 1 minute

RATELIMIT_TWITTER_RATE = 3
RATELIMIT_TWITTER_WINDOW = 60  # 1 minute

RATELIMIT_USER_RATE = 3
RATELIMIT_USER_WINDOW = 60  # 1 minute
RATELIMIT_USER_FREEZE = 300  # 5 minute

RATELIMIT_SEARCH_RATE = 2
RATELIMIT_SEARCH_WINDOW = 1
RATELIMIT_SEARCH_FREEZE = 60  # 1 minute

RATELIMIT_SUGGEST_RATE = 5
RATELIMIT_SUGGEST_WINDOW = 1

RATELIMIT_SUBSCRIBE_RATE = 3
RATELIMIT_SUBSCRIBE_WINDOW = 1

RATELIMIT_POST_LIKE_RATE = 3
RATELIMIT_POST_LIKE_WINDOW = 1
RATELIMIT_POST_FREEZE = 300  # 5 minute

RATELIMIT_GENERAL_RATE = 3
RATELIMIT_GENERAL_WINDOW = 1
